# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181105_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='json',
            field=models.TextField(),
        ),
    ]
