# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181023_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
