# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181105_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='client_ip',
            field=models.TextField(),
        ),
    ]
